### ISSUE TITLE
Milestone 2 feedback: 

### ISSUE THREAD

**Issue by Abu-Hijleh** [data301-2020-winter2/course-project-group_1050#6]
Must fix: 
- [ ] Ryan: missing task 3 in your folder 
- [ ] Vincent: missing folder 
- [ ] Load the data from .csv file in the the data/processed folder instead of using the gist url 
- [ ] project_functions.py does not follow project instructions and should be fixed accordingly 
- [ ] add units to x and y axis, as well as titles to the graphs.
